input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "application" => "incident-analytics-backend" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "incident-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
